### PR TITLE
Add Jane Automapper benchmark

### PR DESCRIPTION
**Pull request by joelwurtz**

### CODE REVIEW

**Comment by tsantos84** [comment]
Could you add the serializer on README?

**Comment by joelwurtz** [comment]
Sure, will do

**Comment by goetas** [comment]
Since https://github.com/php-serializers/ivory-serializer-benchmark/pull/13 has been merged, some extra info needs to be provided in the benchmark file. 

Can you rebase your PR on top of the latest master?

**Comment by tsantos84** [comment]
What about to add link for official pages (or repository) of serializers on README?

**Comment by joelwurtz** [comment]
> What about to add link for official pages (or repository) of serializers on README?

Don't mind doing it, but IMO it should be done in another PR with others repositories link

**Comment by goetas** [comment]
@tsantos84 can it be extracted from the composer metadata ? (`homepage` prop)

**Comment by tsantos84** [comment]
> @tsantos84 can it be extracted from the composer metadata ? (`homepage` prop)

Great idea, but how can we add such information automatically on README?

**Comment by joelwurtz** [comment]
Should be ok with last remarks, also now benchmark result are more close to the TSantos library (it's the same approach so this bench help me to have better performance)

**Comment by tsantos84** [comment]
> Should be ok with last remarks, also now benchmark result are more close to the TSantos library (it's the same approach so this bench help me to have better performance)

That's the purpose of such application. Give insights to developers by increasing the quality and performance of their projects.

**Comment by tsantos84** [comment]
I suppose that this PR can be merged, IMO.

**Comment by goetas** [comment]
right

**Pull request merged**
