### PR TITLE
Small changes on readme

### PR DESCRIPTION
**Pull request by tsantos84**
Small changes on readme

### CODE REVIEW

**Comment by goetas** [comment]
thanks

**Comment by bendavies** [comment]
That 2nd change needs reverting

**Comment by goetas** [comment]
Which one?

**Comment by bendavies** [comment]
`sane -> same` was incorrect

**Comment by tsantos84** [comment]
I've got confused on that sentence:

`with sane defaults setup for benchmarking the serializers`

What did you mean with this?

**Comment by bendavies** [comment]
It means the benchmark config is reasonable or sensible. specifically, warmup, 5 revs + 5 iterations.

**Comment by goetas** [comment]
@bendavies fixed in https://github.com/php-serializers/ivory-serializer-benchmark/commit/42d021315f685bb8dfb54cc32d5d0c5615fbb9f6

**Comment by bendavies** [comment]
👌👌👌

**Comment by tsantos84** [comment]
Understood. Apologies for my mistake.

**Pull request merged**
